# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: check-toml
  - id: end-of-file-fixer

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.4
  hooks:
  - id: gitleaks

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --preserve-quotes
    - --indent=2
    exclude: .pre-commit-config.yaml

- repo: local
  hooks:
  - id: ruff-format
    name: ruff format
    entry: ruff format
    language: system
    types_or: [python, pyi]

  - id: ruff-check
    name: ruff check
    entry: ruff check --fix
    language: system
    types_or: [python, pyi]

  - id: mypy
    name: Validate types with MyPy
    entry: mypy --config-file backend/pyproject.toml --exclude '(jq_kb|dao|backtest/service)' --follow-imports=silent backend/app
    language: system
    types: [python]
    pass_filenames: false
