"""Error code definitions shared by api and core layers."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Application error codes (business-level, not HTTP-level).

    These codes are domain-agnostic and can be used across all modules.
    Each code represents a business error condition.
    """

    # Request errors (1xxx)
    REQUEST_ENTITY_SIZE_TOO_LARGE = "REQUEST_ENTITY_SIZE_TOO_LARGE"
    INVALID_UPLOADED_FILE = "INVALID_UPLOADED_FILE"
    INVALID_PATCH_REQUEST = "INVALID_PATCH_REQUEST"
    INVALID_REQUEST = "INVALID_REQUEST"
    FORBIDDEN = "FORBIDDEN"
    ILLEGAL_STATE = "ILLEGAL_STATE"

    # Resource errors (2xxx)
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    DB_UPDATE_ERROR = "DB_UPDATE_ERROR"
    DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE"

    # Filter errors (3xxx)
    FILTER_REQUIRED_FIELD_MISSING = "FILTER_REQUIRED_FIELD_MISSING"
    FILTER_FIELD_NOT_SUPPORTED = "FILTER_FIELD_NOT_SUPPORTED"
    FILTER_PREDICATE_NOT_SUPPORTED = "FILTER_PREDICATE_NOT_SUPPORTED"
    FILTER_OPERATOR_NOT_SUPPORTED = "FILTER_OPERATOR_NOT_SUPPORTED"

    # Sorter errors (4xxx)
    SORTER_FIELD_NOT_SUPPORTED = "SORTER_FIELD_NOT_SUPPORTED"

    # Authentication errors (5xxx)
    UNAUTHORIZED = "UNAUTHORIZED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"

    # External service errors (6xxx)
    MISSING_PROVIDER_ID = "MISSING_PROVIDER_ID"
    MISSING_PROVIDER_ENTITY = "MISSING_PROVIDER_ENTITY"
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"

    # User-specific errors (7xxx)
    USER_NOT_FOUND = "USER_NOT_FOUND"
    DUPLICATE_EMAIL = "DUPLICATE_EMAIL"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    WEAK_PASSWORD = "WEAK_PASSWORD"
    COMMON_PASSWORD = "COMMON_PASSWORD"
    PASSWORD_MISMATCH = "PASSWORD_MISMATCH"
    OAUTH_USER_NOT_LINKED = "OAUTH_USER_NOT_LINKED"

    # System errors (9xxx)
    INTERNAL_ERROR = "INTERNAL_ERROR"
    SYSTEM_ALREADY_INITIALIZED = "SYSTEM_ALREADY_INITIALIZED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
